run:
  modules-download-mode: readonly

issues:
  new: false
  fix: false
  exclude-rules:
    - path: '_test\.go$'
      linters:
        - funlen
        - gochecknoglobals
        - mnd
        - nestif

severity:
  default-severity: error

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  presets:
    - bugs
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - unused

  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - varnamelen
    - wrapcheck

linters-settings:
  funlen:
    lines: 50
    statements: 30

  gci:
    sections:
      - standard
      - default
      - localmodule

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  goimports:
    local-prefixes: "github.com/13k/dm"

  mnd:
    ignored-functions:
      - 'os\.Create.*'
      - 'os\.Open.*'

  govet:
    enable:
      - shadow

  lll:
    line-length: 120
    tab-width: 2

  nestif:
    min-complexity: 5

  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: true

  wsl:
    allow-assign-and-call: false
    allow-multiline-assign: false
